name: Release Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag that failed and needs to be recreated'
        required: true
        type: string

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            bin_name: convinci
            archive_ext: tar.gz
          - os: macos-latest
            target: x86_64-apple-darwin
            bin_name: convinci
            archive_ext: tar.gz
          - os: macos-latest
            target: aarch64-apple-darwin
            bin_name: convinci
            archive_ext: tar.gz
          - os: windows-latest
            target: x86_64-pc-windows-gnu
            bin_name: convinci.exe
            archive_ext: zip

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install musl (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Package (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          cd target/${{ matrix.target }}/release
          tar czf convinci-${{ matrix.target }}.tar.gz ${{ matrix.bin_name }}

      - name: Package (Windows)
        if: runner.os == 'Windows'
        run: |
          cd target/${{ matrix.target }}/release
          7z a convinci-${{ matrix.target }}.zip ${{ matrix.bin_name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: convinci-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/convinci-${{ matrix.target }}.${{ matrix.archive_ext }}

  create-release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: convinci-*
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/*
          tag_name: ${{ github.ref }}
          body: "Release ${{ github.ref_name }}"